apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GlobalAddress
metadata:
  name: my-globaladdress
spec:
  name: my-globaladdress
  purpose: VPC_PEERING
  addressType: INTERNAL
  prefixLength: 16
  networkRef:
    name: my-network
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
