# Stack configuration
#
# A stack's configuration contains all of its metadata, plus other configuration.

# Behaviors specify what should be done in response to different events.
behaviors:

  engine:
    type: helm2

  crds:
    wordpressinstance.wordpress.samples.stacks.crossplane.io:
      hooks:
        postCreate:
          - directory: configure
        postUpdate:
          - directory: configure

# Metadata
#
# Normally, some of the metadata would be higher up in the document, but for the purposes
# of this demo, the behavioral configuration is at the top instead.
#
# The "type" or "scope" of a stack. This field is commented out as it is still somewhat
# speculative.
# Accepted values: workspace, environment
# type: workspace

# Human readable title of application.
title: Sample Wordpress Stack

overviewShort: Cloud portable Wordpress deployments behind managed Kubernetes and SQL services are demonstrated in this Crossplane Stack.
overview: |-
 This Wordpress stack uses a simple controller that uses Crossplane to orchestrate managed SQL services and managed Kubernetes clusters which are then used to run a Wordpress deployment.
 A simple Custom Resource Definition (CRD) is provided allowing for instances of this Crossplane managed Wordpress Stack to be provisioned with a few lines of yaml.
 The Sample Wordpress Stack is intended for demonstration purposes and should not be used to deploy production instances of Wordpress.

# Maintainer names and emails.
maintainers:
- name: Daniel Suskin
  email: daniel@upbound.io

# Owner names and emails.
owners:
- name: Daniel Suskin
  email: daniel@upbound.io

# Human readable company name.
company: Upbound

# Keywords that describe this application and help search indexing
keywords:
- "samples"
- "examples"
- "tutorials"
- "wordpress"

# Links to more information about the application (about page, source code, etc.)
website: "https://upbound.io"
source: "https://github.com/crossplaneio/sample-stack-wordpress"

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
