---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: sql
spec:
  # The "or" directive in go templates allows for defaulting,
  # but defaulting could also be accomplished using the default values on the schema
  # for a CRD.
  engineVersion: "{{ or .engineVersion "5.7" }}"
