# The claim's metadata and spec fields will be overlaid (in that order) to create
# the template binding.
# The defaults.yaml can be specified to provide default bindings.

# For a GCP Network resource pack, these would be example values that the template would
# use. The only thing a user should need to provide is the project id, though anything
# can be overridden if desired.
network:
  name: example-network

subnetwork:
  name: example-subnetwork
  region: us-central1

provider:
  name: gcp-provider
  namespace: gcp

globaladdress:
  name: example-globaladdress

connection:
  name: example-connection
