# The behaviors configuration specifies how the shared
# controller should respond to various events.
behaviors:
  crds:
    wordpressinstance.wordpress.samples.stacks.crossplane.io/v1alpha1:
      resources:
        - templates/kubernetescluster.yaml
        - templates/mysqlinstance.yaml
        - templates/kubernetesapplication.yaml

      hooks:
        # Triggered if the wordpress instance changed
        postUpdate:
          # Note that this is a list of hooks
          - resources:
              # These are resources that will be rendered using the same context
              # as the other templates, which is to say the target resource will
              # be the source of any configuration/template variable bindings.
              - templates/updatejob.yaml

            # Selectors are the most speculative part of the hook design.
            selectors:
              # In the style of label selectors, the hook will only be called
              # if the selector is satisfied for a particular event:
              - "old.spec.version=2"
              - "new.spec.version=3"
