apiVersion: stacks.crossplane.io/v1alpha1
kind: StackInstall
metadata:
  name: "my-wordpress"
spec:
  # package points to the docker image for the stack.
  #
  # Even though we are using a docker image in the install request,
  # we could also have specified a git url instead.
  package: "crossplane/stack-template-wordpress:master"

  # Speculative design:
  #
  # A stack can also be installed directly from an image or url
  # which does not have its own stack configuration. In that case,
  # the stack configuration can be specified in the stack install itself.
  # configuration:
  #   title: "Wordpress Stack"
  #   behaviors:
  #     crds:
  #     ...
  #
  # The reason the design is speculative is because a lot of questions would
  # need to be answered, and we don't need to answer them yet to get some template
  # stack functionality working. Questions include:
  # * What if the CRD files are not in a stack-friendly location or format?
  # * What if the configuration files are not in a stack-friendly location or format?
  # * Can we get early validation for the configuration which is being passed in?
