# The behaviors configuration specifies how the shared
# controller should respond to various events.
#
# Currently the behaviors configuration only specifies
# what templates should be rendered in response to an
# instance of a known CRD, but it could be used to specify
# other behaviors, such as:
# * Rendering templates at install time (as seen in this example)
# * Updating the status field of an instance of a known CRD
behaviors:
  crds:
    wordpressinstance.wordpress.samples.stacks.crossplane.io/v1alpha1:
      resources:
        - templates/composed-dependencies.yaml

  hooks:
    # These templates are rendered when the stack is installed
    postInstall:
      - resources:
          - templates/composed-prerequisites.yaml
