# The behaviors configuration specifies how the shared
# controller should respond to various events.
#
# Currently the behaviors configuration only specifies
# what templates should be rendered in response to an
# instance of a known CRD, but it could be used to specify
# other behaviors, such as:
# * Rendering templates at install time
# * Updating the status field of an instance of a known CRD
crdOutputs:
  wordpressinstance.wordpress.samples.stacks.crossplane.io/v1alpha1:
    resources:
      - all.yaml
    defaults:
      - defaults.yaml
