apiVersion: stacks.crossplane.io/v1alpha1
kind: StackInstall
metadata:
  name: "my-wordpress"
spec:
  # package points to the docker image for the stack.
  # The stack could also come from a github repo url
  package: "crossplane/stack-template-wordpress:master"

  # Even though we are using a docker image in the install request,
  # we could also have specified a git url instead.
  # url: "github.com/crossplaneio/stack-template-wordpress"
  #
  # A stack can also be installed directly from an image or url
  # which does not have its own stack configuration. In that case,
  # the stack configuration can be specified in the stack install itself.
  # stackConfiguration:
  #   title: "Wordpress Stack"
  #   configure:
  #     - directory: configure/
  #       engine:
  #         type: go-kustomize
  #         configuration:
  #           data:
  #             imageid: "wordpress:5-fpm-alpine"
  #
  # In the case that the stack has a "configure" phase hook, the stack install
  # can also specify configuration to be passed directly to the engine processing
  # the hook. The configuration is namespaced so that it doesn't collide with any
  # other configuration. In a non-install CRD, it would not need to be namespaced
  # so aggressively, because the CRD may only be used for triggering and configuring
  # a resource processing engine.
  # configure:
  #   data:
  #     imageid: "wordpress:5-fpm-alpine"
  #
