---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: wordpress-cluster-wordpress
  labels:
    stack: sample-stack-wordpress
spec:
  writeConnectionSecretToRef:
    name: wordpress-demo-cluster-wordpress